name: Deploy Zola site to Pages

on:
  push:
    branches:
      - main  # Triggers the action when you push to the main branch

permissions:
  contents: write

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures your theme submodule is fetched

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
