# The URL the site will be built for
base_url = "https://stojanov.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
theme = "terminus"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]

[markdown.highlighting]
theme = "terminus"

[extra]
# Put all your custom variables here
